fixtures:
  symlinks:
    profile: "#{source_dir}"
  repositories:
    apache: "git://github.com/puppetlabs/puppetlabs-apache"
    bind: "git://github.com/thias/puppet-bind"
    certs: "git://github.com/rnelson0/certs"
    concat: "git://github.com/puppetlabs/puppetlabs-concat"
    dhcp: "git://github.com/ajjahn/puppet-dhcp"
    epel: "git://github.com/stahnma/puppet-module-epel"
    firewall: "git://github.com/puppetlabs/puppetlabs-firewall"
    lvm: "git://github.com/puppetlabs/puppetlabs-lvm"
    mysql: "git://github.com/puppetlabs/puppetlabs-mysql"
    ntp: "git://github.com/puppetlabs/puppetlabs-ntp"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
