fixtures:
  symlinks:
    profile: "#{source_dir}"
  repositories:
    firewall: "git://github.com/puppetlabs/puppetlabs-firewall"
    stdlib: "git://github.com/puppetlabs/puppetlabs-stdlib"
    apache: "git://github.com/puppetlabs/puppetlabs-apache"
    concat: "git://github.com/puppetlabs/puppetlabs-concat.git"
    ntp: "git://github.com/puppetlabs/puppetlabs-ntp"
